# Generated by Django 3.2.19 on 2023-05-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20230530_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('holidays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='holidays.holidays')),
            ],
        ),
    ]
