# Generated by Django 3.2.19 on 2023-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_auto_20230530_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
